### ISSUE TITLE
Explanation : We need to build a simple app

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/AMS-app#1]
Explanation : We need to build a simple app, with 9 fields in it 
[Бланк заказа запчастей (1).docx](https://github.com/AndroidAkyl/AMS-app/files/1578058/1.docx)
This fields should be included, otherwise - vendors are complaining that they have less info.

**Comment by hasan5151** [comment]
give me more info

**Comment by AndroidAkyl** [comment]
Sure, gonna give more info shortly
